# Generated by Django 4.0.4 on 2022-05-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='seller',
            name='pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
