# Generated by Django 4.0.4 on 2022-05-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_seller_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
