# Generated by Django 4.0.4 on 2022-05-18 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_checkout_checkoutproducts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(blank=True, default=0, null=True)),
                ('final', models.IntegerField(blank=True, default=0, null=True)),
                ('shipping', models.IntegerField(blank=True, default=0, null=True)),
                ('mode', models.CharField(blank=True, max_length=20, null=True)),
                ('paymentstatus', models.CharField(blank=True, max_length=20, null=True)),
                ('orderstatus', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('rppid', models.CharField(blank=True, max_length=50, null=True)),
                ('rpoid', models.CharField(blank=True, max_length=50, null=True)),
                ('rpsid', models.CharField(blank=True, max_length=50, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.buyer')),
                ('products', models.ManyToManyField(to='mainApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='checkoutproducts1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.IntegerField(default=1)),
                ('total', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.product')),
            ],
        ),
        migrations.RemoveField(
            model_name='checkoutproducts',
            name='product',
        ),
        migrations.DeleteModel(
            name='checkout',
        ),
        migrations.DeleteModel(
            name='checkoutproducts',
        ),
    ]
