# Generated by Django 4.0.4 on 2022-05-19 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_checkout_checkoutproducts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='products',
        ),
        migrations.RemoveField(
            model_name='checkoutproducts',
            name='q',
        ),
        migrations.AddField(
            model_name='checkoutproducts',
            name='checkout',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainApp.checkout'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkoutproducts',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='orderstatus',
            field=models.CharField(blank=True, default='Not Packed', max_length=20, null=True),
        ),
    ]
