# Generated by Django 4.0.4 on 2022-05-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_checkoutproducts_delete_checkoutproducts1'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='orderstatus',
            field=models.IntegerField(choices=[(1, 'Not Packed'), (2, 'Packed'), (3, 'Out For Delivery'), (4, 'Delivered')], default=1),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='paymentstatus',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Done')], default=1),
        ),
    ]
