# Generated by Django 4.0.4 on 2022-05-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_checkout_active_alter_checkout_orderstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('phone', models.IntegerField()),
                ('subject', models.CharField(max_length=80)),
                ('desc', models.CharField(max_length=250)),
            ],
        ),
    ]
