# Generated by Django 4.0.4 on 2022-05-26 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0022_alter_buyer_email_alter_seller_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='orderstatus',
        ),
        migrations.AddField(
            model_name='checkoutproducts',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='checkoutproducts',
            name='orderstatus',
            field=models.IntegerField(choices=[(1, 'Not Packed'), (2, 'Packed'), (3, 'Out For Delivery'), (4, 'Delivered')], default=1),
        ),
        migrations.AddField(
            model_name='checkoutproducts',
            name='seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainApp.seller'),
            preserve_default=False,
        ),
    ]
