# Generated by Django 4.0.4 on 2022-05-26 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0023_remove_checkout_orderstatus_checkoutproducts_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutproducts',
            name='seller',
        ),
    ]
