# Generated by Django 4.0.4 on 2022-05-26 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0026_remove_checkout_orderstatus_checkoutproducts_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutproducts',
            name='seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainApp.seller'),
            preserve_default=False,
        ),
    ]
